Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "192.168.50.10"

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
          "db" => ["dbserver"],
          "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
      }
    end
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "192.168.50.20"
    app.vm.network :forwarded_port, guest: 80, host: 8003
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/site.yml"
      ansible.groups = {
          "app" => ["appserver"],
          "app:vars" => { "db_int_ip" => "192.168.50.10"}
      }
      ansible.extra_vars = {
          "deploy_user" => "vagrant",
          "sites" => {
              "default" => [
                  "listen 80",
                  "server_name app",
                  "location / { proxy_pass http://127.0.0.1:9292; }"]
          }
      }
    end
  end
end
